#+title: Awesome Boxes
#+date: <2016-11-22 mar.>

Awesome Boxes is all about drawing boxes around text to alert your
readers about something particular. The specific aim of this package is
to use [[http://fontawesome.io/icons/][FontAwesome]] icons to ease the illustration of these boxes.

This means all the magic of this package only exists if you previously
installed FontAwesome on your system and made it available for use with
XeTeX. Yes, this package require you to use XeLaTeX too.

We use the previous work of Honza Ustohal on [[https://gist.github.com/sway/3101743][fontawesome.sty]] to build
this package. However, we made two important modifications:

 1. we rename the internal commands of ~fontawesome.sty~ from ~\fa~ to
    ~\abIcon~ and the ~\FA~ font switch to ~\ABFamily~ to avoid
    collision if you want to use both of them;
 2. we remove most of the provided icons to only kept the one we really
    use in this package.

For more details, please refer to the [[https://github.com/milouse/latex-awesomebox/blob/master/awesomebox.pdf][awesomebox.pdf]] document.

* Requirements

 - a working XeLaTeX environment
 - [[http://fontawesome.io/icons/][FontAwesome]]

* Installation

Download the ~awesomebox.sty~ file and put it in the same folder of the
document your are composing.

For system wide installation, please refer to the documentation of your
XeLaTeX distribution.
