#+title: Awesome Boxes
#+options: toc:nil
#+language: en

Awesome Boxes is all about drawing admonition blocks around text to
inform or alert your readers about something particular. The specific
aim of this package is to use [[https://fontawesome.com][FontAwesome 5]] icons to ease the
illustration of these blocks.

The idea of admonition blocks comes from the ones you can easily do with
[[https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/][AsciiDoc]].

For more details, please refer to the [[https://git.umaneti.net/latex-awesomebox/plain/awesomebox.pdf][awesomebox.pdf]] document.

#+html: <a href="https://liberapay.com/milouse/donate"><img alt="Support using Liberapay" src="https://img.shields.io/badge/Liberapay-Support_me-yellow?logo=liberapay"/></a>
#+html: <a href="https://paypal.me/milouse"><img alt="Support using Paypal" src="https://img.shields.io/badge/Paypal-Support_me-00457C?logo=paypal&labelColor=lightgray"/></a>

If you like my work, you can help me a lot by giving me some tip, either
through [[https://liberapay.com/milouse][Liberapay]] or [[https://paypal.me/milouse][Paypal]]. Thank you very much!

* Requirements

The following LaTeX packages are required (they should be already
included in your LaTeX distribution):

- ~array~
- ~fontawesome5~
- ~ifthen~
- ~xcolor~
- ~xparse~

* Installation

Download the ~awesomebox.sty~ file and put it in the same folder of the
document your are composing.

For system wide installation, please refer to the documentation of your
LaTeX distribution.

* Compatibility

This repository also hosts the package ~awesomebox-compat~, which
depends on the ~fontawesome~ package, instead of ~fontawesome5~. Apart
from that, it has the exact same features set.

This can be useful for you if you want to use it with an old LaTeX
distribution, which does not embed ~fontawesome5~ yet (like Overleaf
system). To use it, download the file ~awesomebox-compat.sty~ in this
repository, put it near your tex files and just replace your
~\usepackage{awesomebox}~ instruction by
~\usepackage{awesomebox-compat}~.

Be aware that icon names changes between FontAwesome and FontAwesome5
and thus using the compatibility package may break your current
files. FontAwesome also requires you to use XeLaTeX or LuaTeX: you
cannot use PDFLaTeX with the compatibility package.

* Contribution

See [[./CONTRIBUTING.org][CONTRIBUTING file]].

* License

Awesome Box is released under the [[http://www.wtfpl.net/txt/copying/][WTFPL]]. A copy of this license is
distributed in this package.
