#+title: Awesome Boxes
#+date: <2019-03-24 sam.>

Awesome Boxes is all about drawing admonition blocks around text to
inform or alert your readers about something particular. The specific
aim of this package is to use [[https://fontawesome.com][FontAwesome 5]] icons to ease the
illustration of these blocks.

The idea of admonition blocks comes from the ones you can easily do with
[[http://asciidoctor.org/docs/user-manual/#admonition][AsciiDoc]].

For more details, please refer to the [[https://github.com/milouse/latex-awesomebox/blob/master/awesomebox.pdf][awesomebox.pdf]] document.

* Requirements

The following LaTeX packages are required (they should be already
included in your LaTeX distribution):

- ~fontawesome5~
- ~xcolor~
- ~array~
- ~xparse~

* Installation

Download the ~awesomebox.sty~ file and put it in the same folder of the
document your are composing.

For system wide installation, please refer to the documentation of your
LaTeX distribution.

* License

Awesome Box is released under the [[http://www.wtfpl.net/txt/copying/][WTFPL]]. A copy of this license is
distributed in this package.
